[project]
name = "network-scanner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "netifaces>=0.11.0",
    "ping3>=4.0.8",
    "pyinstaller>=6.12.0",
]
