name: Build Windows Release

on:
  push:
    tags:
      - 'v*'  # Trigger on new version tags

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      run: uv python install

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Build Windows EXE
      run: |
        .venv\Scripts\activate
        pyinstaller --onefile --name=network-scanner --console --icon=icon.ico main.py

    - name: Create Release Draft
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: true
        prerelease: false

    - name: Upload Windows Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/network-scanner.exe
        asset_name: network-scanner-${{ github.ref_name }}-windows-amd64.exe
        asset_content_type: application/vnd.microsoft.portable-executable
